### ISSUE TITLE
Identify telemetry attributes that aren't useful

### ISSUE THREAD

**Issue by parfa30** [desihub/desiperf#39]

**Comment by apaat** [comment]
Removed the following attributes referencing non-existent sensors:
-chimney_ib/im/it/os/ow_temp, probe1/2_temp/humidity

Removed the following attributes referencing telescope status, rather than plotable numbers:
lights_high/low,mirror_covers,mirror_status,sutter_upper/lower

Found 1 attributes ('mirror_rtd_temp') which I think it referencing a working sensor but the data being recorded is bad.

Found multiple timestamp attributes that are not being properly read from the fp files (telescope/dome/tower_timestamp)

**Comment by parfa30** [comment]
Will close after I get this list removed from the data source.
